### ISSUE TITLE
Include packages in systemPackages?

### ISSUE THREAD

**Issue by bbarker** [justinwoo/easy-purescript-nix#101]
I'd like to do something like this in a container:

```nix
  containers.mypyPurs =
  { autoStart = true;
    privateNetwork = true;
    config = { config, pkgs, ... }: {
      environment.systemPackages = with pkgs; [
        # Shells:
        bash
        # For PureScript:
        # haskellPackages.purescript # using easy-ps instead:
        easy-ps.purs
        easy-ps.spago
        # For mypy/Python
        mypy
        python38Full
        python38Packages.virtualenv
      ];
```

I was using the described method to define `easy-ps`: https://github.com/justinwoo/my-blog-posts/blob/master/posts/2018-10-24-using-purescript-easily-with-nix.md#using-this-from-downstream-projects

However, when I try to add to `systemPackages` as shown, I get an error:

>  value is a function while a set was expected,

Any suggested workarounds?

**Comment by justinwoo** [comment]
is this related to https://github.com/justinwoo/easy-purescript-nix#breaking-change-jul-02-2019? what is `easy-ps` here?

**Comment by bbarker** [comment]
@justinwoo I defined `easy-ps` like:

```
let
  easy-ps = import (pkgs.fetchFromGitHub {
    owner = "justinwoo";
    repo = "easy-purescript-nix";

    # at this git revision:
    rev = "340e82b";

    # this sha can be obtained by using
    # nix-prefetch-git https://github.com/justinwoo/easy-purescript-nix.git --rev 340e82b
    # (without --rev for latest master)
    sha256 = "1q2ciwd3193kig1paidzrgxl60y4rb39bsi97lk7m6ff8mis6z6i";
  });

```
Woops, you are right, appending 

``` {
    inherit pkgs;
  };```

fixed the issue.
