### ISSUE TITLE
buildInputs: value is a function while a set was expected

### ISSUE THREAD

**Issue by rubenmoor** [justinwoo/easy-purescript-nix#112]
I upgraded to master and upon running `nix-shell` I get the error message:

    error: value is a function while a set was expected, at `default.nix:8:17`

This refers to the line

      buildInputs = easy-ps.buildInputs;

Full context:

This is my `default.nix`:

    { pkgs ? import <nixpkgs> {} }:
    
    let
      easy-ps = import ./easy-ps.nix { inherit pkgs; };
    
    in pkgs.stdenv.mkDerivation {
      name = "nerg";
      buildInputs = easy-ps.buildInputs;
    }

And this is my `easy-ps.nix`:

    { pkgs ? import <nixpkgs> {} }:
    
    import (pkgs.fetchFromGitHub {
        owner = "justinwoo";
        repo = "easy-purescript-nix";
        rev = "47507b27e15a9c3b929111cf43d2e9c0e4b97f4c";
        sha256 = "0gnwymgm4i5y9vknpcsr99pwy76w14nclqxb6xmmzlw2s8fx85hm";
    })

**Comment by justinwoo** [comment]
I recently removed the old deprecation notice from a year ago today: https://github.com/justinwoo/easy-purescript-nix/commit/90dccf69e8b9c09459053c182e9dc14d020e897d#diff-04c6e90faac2675aa89e2176d2eec7d8

**Comment by rubenmoor** [comment]
thanks! your README.md reflects that, some part of your blogpost not yet.
