### ISSUE TITLE
pulp

### ISSUE THREAD

**Issue by jamesdbrock** [justinwoo/easy-purescript-nix#113]
`pulp` is required to publish packages to Pursuit, right? I'd like to have `pulp` in my `shell.nix`.

Following the template of

https://github.com/justinwoo/easy-purescript-nix/blob/93b47add383c6cf51f4abcd26e5c663a344e5212/remote-test.nix#L17

I have in my `shell.nix` something like this:

```
  buildInputs = [
    remote.purs-0_13_8
    remote.psc-package
    remote.spago
    pkgs.nodejs-13_x
    pkgs.nodePackages.bower
    pkgs.nodePackages.pulp
  ];
```

but `nix-shell` fails like this while trying to make `pulp`:

```
> install-purescript --purs-ver=0.12.5

sh: install-purescript: command not found
npm ERR! code ELIFECYCLE
npm ERR! syscall spawn
npm ERR! file sh
npm ERR! errno ENOENT
npm ERR! purescript@0.12.5 postinstall: `install-purescript --purs-ver=0.12.5`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the purescript@0.12.5 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /build/.npm/_logs/2020-07-26T14_31_35_943Z-debug.log

builder for '/nix/store/nczy5zk99zy0sa7bdc4ls9h4knnfq3vv-node_pulp-14.0.0.drv' failed with exit code 1
```

I note that this seems to be doing the wrong thing anyway, it looks like it's trying to build a version of `purs` which I don't want.

Advice on how to get `pulp` in my `shell.nix`? Or how to publish to Pursuit without `pulp`?

**Comment by jamesdbrock** [comment]
This work for running `pulp` in the `nix-shell shell.nix` though, so maybe that's good enough.
```
npm install pulp
node node_modules/pulp/index.js 
```

**Comment by justinwoo** [comment]
right, i think you will want to just use pulp from npm and install it via npm or yarn. there is a derivation in nixpkgs nodePackages.pulp but it is regularly out of date, and as a result, probably will do the wrong thing. i might eventually add pulp into this project too, since i recently fixed the pscid derivation, but let's see if this is really necessary at all
