### ISSUE TITLE
Make it easy to override Node version

### ISSUE THREAD

**Issue by toastal** [justinwoo/easy-purescript-nix#125]
Currently everything defaults to `node-12_x`, but we are using `14.x` in our project. The `pscid/default.nix` allows `nodejs` to be overridden but when `easy-purescript` is being consumed via `buildInputs [ easy-purescript.pscid ]`, `nodejs` is not overridable.

**Comment by justinwoo** [comment]
please just import the expression and use it yourself https://github.com/justinwoo/easy-purescript-nix/blob/c8c32741bc09e2ac0a94d5140cf51fa5de809e24/pscid/default.nix
