### ISSUE TITLE
Support OSX

### ISSUE THREAD

**Issue by justinwoo** [justinwoo/easy-purescript-nix#13]
I don't use OSX, but these derivations mostly could depending. There are some isDarwin helpers and such in nixpkgs standard library that you can use for this.

Could be added to build matrix on Travis too.

**Comment by justinwoo** [comment]
Looks about right, the only difference I would want actually is to remove even my own usage of interpolated strings and just have separate fetchurl calls

**Comment by boxyoman** [comment]
I think I made the changes you wanted.

**Comment by justinwoo** [comment]
Fixed by #20
