### ISSUE TITLE
Problem with libtinfo

### ISSUE THREAD

**Issue by ursi** [justinwoo/easy-purescript-nix#135]
I get the following error when running `purs` from the `0.14.1` purescript package
```
$ result/bin/purs
result/bin/purs: /nix/store/cr4d9p20fy7npry1cyjppksjvb79xag1-ncurses-6.1-20190112-abi5-compat/lib/libtinfo.so.5: no version information available (required by result/bin/purs)
```
Though, the command seems to still work regardless

**Comment by justinwoo** [comment]
![image](https://user-images.githubusercontent.com/2396926/116256203-a66e6200-a77b-11eb-88bc-c5a741767a47.png)

looks like something they introduced upstream
