### ISSUE TITLE
Re-add purty when a reliable mirror exists

### ISSUE THREAD

**Issue by toastal** [justinwoo/easy-purescript-nix#140]
Bintray, where `purty` is currently being released, is down and as a result `purty` was understandably removed from the `easy-purescript-nix` project (see closed issue #137 and merged PR #139).

I always use `purty` when writing PureScript because I'm now accustomed to autoformatters like `elm-format` and `eslint`. I opened an [issue on `purty`'s GitLab repo](https://gitlab.com/joneshf/purty/-/issues/242) to perhaps migrate to GitLab's generic repositories so that there would only be a single point of failure for binary upload and source code. Luckily, `purty` still exists in my binary cache for now.

If anyone is familiar with Bazel+GitLab CI, this could be a solution. It would be a nice re-addition to have `purty` (regardless of beta-quality) back in the tooling for users.

**Comment by paluh** [comment]
I'm not sure if using npm registry as a binary source is acceptable in the case of _easy-purescript-nix_. @justinwoo could you please tell me what do you think? I can provide a PR if it is the case - I've this version working here:

https://gist.github.com/paluh/6154e1e6c2274b6115bf22702df50b45

Could be tested with:

```nix
let
      purty = import (pkgs.fetchurl {
        url = "https://gist.githubusercontent.com/paluh/6154e1e6c2274b6115bf22702df50b45/raw/07beaa1d4aa6445131b16325b1074c9948fc4a22/purty.nix";
        sha256 = "0hcyzz9ddkahrlwhlgayjfap1vrpbma0vmp9zf187ahx606pil9p";
      }) { pkgs = pkgs; };
  ...
in

**Comment by justinwoo** [comment]
yeah i think other existing derivations use it as a source also anyway

**Comment by paluh** [comment]
@toastal I think that we can close this issue as @justinwoo merged my PR.
