### ISSUE TITLE
add bower

### ISSUE THREAD

**Issue by pmd3d** [justinwoo/easy-purescript-nix#194]
hi. I'm new to Purescript so I'm not sure if this makes sense:

cloned the repository
nix-shell ./ci.nix
mkdir test
cd test
pulp init

Error message:
ERROR: No `bower` executable found.

Pulp no longer bundles Bower. You'll need to install it manually:
npm install -g bower

I was hoping to try out the pulp browserify feature. I don't believe that is in spago yet. If you have a workaround, I will try it.

**Comment by justinwoo** [comment]
you should add bower to your environment by adding bower to your own nix shell or installing bower globally from npm

**Comment by justinwoo** [comment]
you might want to review some resources on how to use nix https://github.com/justinwoo/nix-shorts

**Comment by jamesdbrock** [comment]
Here's an example `shell.nix` which includes `bower`:

```nix
# Universal shell for PureScript repos
# { pkgs ? import <nixpkgs> { }
{ pkgs ? import (builtins.fetchGit {
  # https://github.com/NixOS/nixpkgs/releases/tag/21.11
  url = "https://github.com/nixos/nixpkgs/";
  ref = "refs/tags/21.11";
  rev = "a7ecde854aee5c4c7cd6177f54a99d2c1ff28a31";
  }) { }
}:
let
  easy-ps = import (builtins.fetchGit {
    url = "https://github.com/justinwoo/easy-purescript-nix.git";
    ref = "master";
    rev = "9c5ffd3e54c41dece66ed84f8f23970a4f1f3883";
  }) { inherit pkgs; };
in
pkgs.mkShell {
  nativeBuildInputs = [
    easy-ps.purs-0_14_7
    easy-ps.spago
    easy-ps.pulp
    easy-ps.psc-package
    easy-ps.purs-tidy
    pkgs.nodejs-17_x
    pkgs.nodePackages.bower
  ];
  LC_ALL = "C.UTF-8"; # https://github.com/purescript/spago/issues/507
  # https://github.com/purescript/spago#install-autocompletions-for-bash
  shellHook = ''
    source <(spago --bash-completion-script `which spago`)
  '';
}

```
