### ISSUE TITLE
Purs probably needs patchelfing

### ISSUE THREAD

**Issue by MasseR** [justinwoo/easy-purescript-nix#3]
The purs binary has missing libraries, patchelf should be able to help here

```
$ ldd /nix/store/g0bimx9bfl1dis5hkn5naq1nddwscd9b-purs-simple/bin/purs
	linux-vdso.so.1 (0x00007ffffb7fd000)
	libm.so.6 => /nix/store/fg4yq8i8wd08xg3fy58l6q73cjy8hjr2-glibc-2.27/lib/libm.so.6 (0x00007f76a4bd5000)
	libz.so.1 => not found
	libtinfo.so.5 => not found
	librt.so.1 => /nix/store/fg4yq8i8wd08xg3fy58l6q73cjy8hjr2-glibc-2.27/lib/librt.so.1 (0x00007f76a49cd000)
	libutil.so.1 => /nix/store/fg4yq8i8wd08xg3fy58l6q73cjy8hjr2-glibc-2.27/lib/libutil.so.1 (0x00007f76a47ca000)
	libdl.so.2 => /nix/store/fg4yq8i8wd08xg3fy58l6q73cjy8hjr2-glibc-2.27/lib/libdl.so.2 (0x00007f76a45c6000)
	libgmp.so.10 => not found
	libpthread.so.0 => /nix/store/fg4yq8i8wd08xg3fy58l6q73cjy8hjr2-glibc-2.27/lib/libpthread.so.0 (0x00007f76a43a7000)
	libgcc_s.so.1 => /nix/store/fg4yq8i8wd08xg3fy58l6q73cjy8hjr2-glibc-2.27/lib/libgcc_s.so.1 (0x00007f76a4191000)
	libc.so.6 => /nix/store/fg4yq8i8wd08xg3fy58l6q73cjy8hjr2-glibc-2.27/lib/libc.so.6 (0x00007f76a3ddd000)
	/lib64/ld-linux-x86-64.so.2 => /nix/store/fg4yq8i8wd08xg3fy58l6q73cjy8hjr2-glibc-2.27/lib64/ld-linux-x86-64.so.2 (0x00007f76a4f6a000)
```

**Comment by justinwoo** [comment]
https://github.com/srdqty/purescript-project-template/blob/902f3e7c5ec4284a0878cb4806553e3756552231/nix/pkgs/purescript/default.nix cc @srdqty

**Comment by kaitanie** [comment]
I did some patchelfing for purs, purp and psc-package (https://github.com/kaitanie/easy-purescript-nix/tree/nixos-experiment). Now those binaries and also the static dhall binaries that didn't need patching seem to work in NixOS.

The psc-package2nix perl script doesn't work yet though... it needs some dependencies from nixpkgs (things like jq).

**Comment by justinwoo** [comment]
Yeah, it'll need jq and perl. Maybe adding those to the derivation would be good, but I at least like not having to download perl separately from my system.

**Comment by MasseR** [comment]
One of the main selling points of nix is having a sandboxed environment, so having perl come from nixpkgs makes sense.

I would personally either use nixpkgs as is, or use a pinned version of nixpkgs to make sure the underlying libs don't change.

**Comment by justinwoo** [comment]
Just using nixpkgs and allowing for pkgs to be overridden sounds fine

**Comment by justinwoo** [comment]
https://github.com/justinwoo/psc-package2nix/issues/5

**Comment by justinwoo** [comment]
Okay, psc-package is now updated from https://github.com/justinwoo/psc-package2nix/pull/6 to wrap the program with the concrete PATHs

**Comment by MasseR** [comment]
Thanks for reminding! Works now
