### ISSUE TITLE
update README

### ISSUE THREAD

**Issue by justinwoo** [justinwoo/easy-purescript-nix#32]
need to do this at some poin

**Comment by mtesseract** [comment]
Hi,

what is the scope? I did have a look at the linked repository https://github.com/justinwoo/spacchetti-react-basic-starter but couldn't find any Nix related setup in there? Did I overlook something or does this repository's README need some work in this regard?

Thanks,
Moritz

**Comment by justinwoo** [comment]
oh, sorry, nix things were removed from that repo because of many complaints. i'll try to remove any remaining references. you might look at this repo instead: https://github.com/justinwoo/vidtracker

**Comment by mtesseract** [comment]
cool, thanks!

**Comment by justinwoo** [comment]
Closed for cleanup, but this could definitely use some various incremental improvements.
