### ISSUE TITLE
script to update packages

### ISSUE THREAD

**Issue by srghma** [justinwoo/easy-purescript-nix#46]
add scripts to update packages

e.g. I always add `update.sh` script to update `revision.json`/other logic

example https://github.com/srghma/dotfiles/blob/master/nixos/pkgs/dunsted-volume/update.sh

this way I dont need to look for new commit, paste it in nix file, make `nix-build`, then update expected hash

I just run `update.sh` and that's all

____________

Why I suggest this:
1. to allewiate steps above
2. there is no info how pscid is generated and how to update it

N.B. it would be good to have some script `update-everything.sh` that would run all `update.sh` scripts in repo

**Comment by justinwoo** [comment]
Closed for issue cleanup
