### ISSUE TITLE
Build fails due to pscid bower packages

### ISSUE THREAD

**Issue by justinwoo** [justinwoo/easy-purescript-nix#48]
@jmackie could you fix this issue?

**Comment by justinwoo** [comment]
https://travis-ci.com/justinwoo/easy-purescript-nix/builds/113703374

**Comment by justinwoo** [comment]
@vyorkin did you have any luck updating this? Or this could also just be removed or skipped for testing in CI.

**Comment by vyorkin** [comment]
not yet, sorry, but I was going to try again today evening

**Comment by jmackie** [comment]
Apologies for the slow response - I might have some time this afternoon to fix it, otherwise I'll leave it to @vyorkin :+1:

**Comment by vyorkin** [comment]
It seems this should wait for https://github.com/kRITZCREEK/pscid/issues/52
