### ISSUE TITLE
How to update purs and spago ?

### ISSUE THREAD

**Issue by yuanw** [justinwoo/easy-purescript-nix#81]
Hey,

I guess this is more a nix question, how do I update the purs and spago

I tried `nix-env -f . -uA spago` or `nix-env -f . -uA purs-simple`, they don't work. I have to `nix-env -e purs-simple` first, and re-install purs and spago. If there any works to update them ? 

Thank you

**Comment by srghma** [comment]
what you are trying to accomplish?

btw, I have a fork with update script if this is what you are looking for https://github.com/srghma/easy-purescript-nix/blob/6f4b258eb7641736b9663ee58d44fc029c892d8a/Makefile#L41

**Comment by justinwoo** [comment]
Please don't come here to advertise your fork

**Comment by srghma** [comment]
I came here to see new features you have added here and saw this issue, though this would be helpful

you can delete my message if you want

**Comment by justinwoo** [comment]
`nix-env -e` will match using some regex patterns. from `man nix-env`:

```
OPERATION --UNINSTALL
   Synopsis
       nix-env {--uninstall | -e} drvnames...

   Description
       The uninstall operation creates a new user environment, based on the current generation of the active profile,
       from which the store paths designated by the symbolic names names are removed.

   Examples
           $ nix-env --uninstall gcc
           $ nix-env -e '.*' (remove everything)
```

if you have derivations of the same attribute name, you should be able to install different derivations by simply installing using the files. see also https://github.com/justinwoo/nix-shorts/blob/master/posts/install-things-to-nix-profile.md

you might also want to ask nixos discourse for a more detailed answer: https://discourse.nixos.org/

**Comment by yuanw** [comment]
thank you for the answer
